### ISSUE TITLE
Audio APIをもう少しまじめに検討する

### ISSUE THREAD

**Issue by kiikura** [r-stack/hub#1]
ざっくりノードの関係を書くとこんな感じじゃない？panは省略してもいいと思うけどデモでオーケストラやるならほしいかも。

![image](https://cloud.githubusercontent.com/assets/5870381/26786254/f17e759c-4a40-11e7-8efe-31c61add2cc9.png)

**Comment by kwbt69** [comment]
すげー、、ヴィジュアライザーでる。

デモでは最低2声、できれば3声の合奏にしたい。例えば、ピアノ+ピアニカ、コンバス+ピアノ+ギター、みたいな。

**Comment by kiikura** [comment]
出るかは知らんけどビジュアルは音量レベル程度を想定です。
トラック数は性能的にもそれくらいが現実ラインだと思う。

**Comment by kiikura** [comment]
間違ってたところと　@kmorihiro のrecorder.js使う前提に修正。  
あとは録音結果を確認する専用のトラックを用意して下記ぐらいに分割すればよいかと。

- deck(全体制御）
- track（各トラック制御）
- rec (録音専用トラック制御）

![image](https://cloud.githubusercontent.com/assets/5870381/26809463/f6f78ef0-4a9f-11e7-950c-e36007b0a09c.png)

**Comment by kiikura** [comment]
実装と上の絵ちょっと違うけど、まあ大体できたのでクローズ
