### ISSUE TITLE
firebase.databaseのlikesの更新権限がまちがっている

### ISSUE THREAD

**Issue by kiikura** [r-stack/hub#14]
そもそも厳密にルールできない気がするけどtrackレコードの更新は現状だとplayer自身しかダメになっている。likesプロパティは誰でも更新ＯＫにするべき。

**Comment by kwbt69** [comment]
うーん、確かに。ただ、サーバーサイドでリクエストを検証しないと、イタズラできちゃいますね。

**Comment by kiikura** [comment]
まーね。認証しないで「いいね」できるんで。likesプロパティだけいきなり100とかに更新する輩がいるかもって意味だよね？（validate Ruleで+1しか許可しないとかはできるよ）

認証あり、一人一票でやるなら、incrementと同時に投票済み辞書をもってて、ユーザIDつっこんでvalidateルールでincrement縛りにすればできるとは思う（firebaseのチュートリアルはそーなってる）。

仕様の問題ですね。

realtime databaseの ルール定義むずかしくない？　昨日小一時間ほどはまったよ。

**Comment by kwbt69** [comment]
Realtime databaseのルール定義書いてると、sendmailのマクロの方がマシに見えますね。ほとんどパズルですよ。
チュートリアルにあったんですね、、でも実装は優先度低めでいきたい。

**Comment by kiikura** [comment]
うん、とりあえずコンソールに入れたら該当箇所だけtrue設定しちゃうつもり。このIssueは備忘録。
