### ISSUE TITLE
ログインすると中身が空っぽだぜ

### ISSUE THREAD

**Issue by kwbt69** [r-stack/hub#24]
![welcome to hub](https://user-images.githubusercontent.com/5164930/27953887-790f538a-6348-11e7-98c6-f8b74bb1a92e.png)

**Comment by kiikura** [comment]
/トップはローディング画面用に空けてる

フルパスで

**Comment by kiikura** [comment]
/playrooms/p1

ね

**Comment by kwbt69** [comment]
:+1:

**Comment by kiikura** [comment]
スプラッシュ画面的なものを作る。時間間に合わなければ、playroom一覧に飛ばす。
