### ISSUE TITLE
サーバー側を実装する

### ISSUE THREAD

**Issue by kiikura** [r-stack/hub#9]
とりあえず実現方式から検討する。

裏目的のサーバーレスがあるのでfirebaseで検討してみる

**Comment by kiikura** [comment]
他の人が録音したのが見えればとりあえずOK

**Comment by kiikura** [comment]
@kwbt69 firebaseプロジェクトとgcpのプロジェクトって関連付けかたわかる？

**Comment by kiikura** [comment]
同じ名前入れたらOKだった

**Comment by kwbt69** [comment]
@kiikura oh, sorry... 既にrhd2017-hubで作っててかぶってたので、こっちを使ってください。Invitationいってるはずです。

**Comment by kiikura** [comment]
feature/firebaseで作業します。少しかかりそうなのでWIPで時々マージします。

- [x] publicフォルダに公開する部分を移動する
- [x] 認証を作る（githubで認証を想定）
- [x] Trackの参照（DBから取得する）
- [x] PlayRoomの参照
- [x] Trackの登録、更新
- [x] SPA化する

**Comment by kiikura** [comment]
まあベースはできたのでクローズ
